// ChronoLux - Qo'l soatlari ma'lumotlar bazasi
const WATCH_PRODUCTS = [
  {
    id: 1,
    name: "Rolex Submariner Date",
    brand: "Rolex",
    category: "erkaklar",
    mechanism: "Avtomatik mexanika",
    caseMaterial: "Oystersteel zanglamas po'lat",
    strapMaterial: "Chelik (Oyster)",
    dialColor: "Qora",
    waterResistance: "300 metr / 30 ATM",
    glass: "Sapfir kristall (Siklops linzali)",
    diameter: "41 mm",
    price: 182000000, // so'mda
    oldPrice: 198000000,
    rating: 4.9,
    reviewsCount: 42,
    badge: "Bestseller",
    badgeType: "hot",
    image:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
    description:
      "Rolex Submariner — dunyodagi eng mashhur va nufuzli dayverlik soati. 300 metrgacha suv o'tkazmaydi, Cerachrom keramik bezel va o'zini o'zi buraydigan Calibre 3235 mexanizmi bilan jihozlangan.",
  },
  {
    id: 2,
    name: "Patek Philippe Nautilus 5711",
    brand: "Patek Philippe",
    category: "klassik",
    mechanism: "Avtomatik mexanika",
    caseMaterial: "Zanglamas po'lat",
    strapMaterial: "Integrallashgan po'lat",
    dialColor: "Moviy gradient",
    waterResistance: "120 metr / 12 ATM",
    glass: "Sapfir (ikki tomonlama)",
    diameter: "40 mm",
    price: 495000000,
    oldPrice: 530000000,
    rating: 5.0,
    reviewsCount: 19,
    badge: "Eksklyuziv",
    badgeType: "exclusive",
    image:
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80",
    description:
      "Nautilus — lyuks sport soatlarining afsonaviy cho'qqisi. Gerald Genta tomonidan yaratilgan port-teshik shaklidagi korpus va moviy gilyoshir terish unga takrorlanmas nafislik beradi.",
  },
  {
    id: 3,
    name: "Omega Speedmaster Moonwatch",
    brand: "Omega",
    category: "erkaklar",
    mechanism: "Mexanik (qo'lda burash)",
    caseMaterial: "Zanglamas po'lat",
    strapMaterial: "Po'lat bilaguzuk",
    dialColor: "Mat qora",
    waterResistance: "50 metr / 5 ATM",
    glass: "Hesalit shisha / Sapfir",
    diameter: "42 mm",
    price: 96000000,
    oldPrice: 108000000,
    rating: 4.8,
    reviewsCount: 38,
    badge: "Tarixiy",
    badgeType: "featured",
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    description:
      "Oyga qadam qo'ygan birinchi soat. NASA tomonidan kosmik parvozlar uchun sertifikatlangan, Calibre 3861 xronograf mexanizmi bilan ishlaydi.",
  },
  {
    id: 4,
    name: "Tissot PRX Powermatic 80",
    brand: "Tissot",
    category: "erkaklar",
    mechanism: "Avtomatik mexanika",
    caseMaterial: "316L zanglamas po'lat",
    strapMaterial: "Integrallashgan po'lat",
    dialColor: "To'q ko'k vafli",
    waterResistance: "100 metr / 10 ATM",
    glass: "Qirilmaydigan sapfir",
    diameter: "40 mm",
    price: 9800000,
    oldPrice: 11200000,
    rating: 4.9,
    reviewsCount: 86,
    badge: "Hit Mahsulot",
    badgeType: "hot",
    image:
      "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80",
    description:
      "1978-yilgi retro dizaynning zamonaviy talqini. 80 soatlik quvvat zaxirasiga ega Shveysariya Powermatic 80 mexanizmi va ajoyib geometrik dizayn.",
  },
  {
    id: 5,
    name: "Cartier Ballon Bleu De Cartier",
    brand: "Cartier",
    category: "ayollar",
    mechanism: "Avtomatik mexanika",
    caseMaterial: "18K pushti oltin va po'lat",
    strapMaterial: "Tabiiy alligatr terisi",
    dialColor: "Kumushrang gilyosh",
    waterResistance: "30 metr / 3 ATM",
    glass: "Sapfir",
    diameter: "36 mm",
    price: 115000000,
    oldPrice: 125000000,
    rating: 4.9,
    reviewsCount: 27,
    badge: "Yangi",
    badgeType: "new",
    image:
      "https://images.unsplash.com/photo-1517462964-21fdcec3f25b?auto=format&fit=crop&w=800&q=80",
    description:
      "Nozik ayollar uchun tengsiz zargarlik san'ati namunasi. Moviy sapfir kaboshonli himoyalangan toj va Rim raqamlari bilan bezatilgan klassik terish.",
  },
  {
    id: 6,
    name: "Hublot Big Bang Unico Titanium",
    brand: "Hublot",
    category: "mexanik",
    mechanism: "Skeleton avtomatik",
    caseMaterial: "Yengil titan va keramika",
    strapMaterial: "Strukturaviy kauchuk",
    dialColor: "Mat skeleton",
    waterResistance: "100 metr / 10 ATM",
    glass: "Sapfir (nur qaytarmaydigan)",
    diameter: "44 mm",
    price: 245000000,
    oldPrice: 270000000,
    rating: 4.7,
    reviewsCount: 15,
    badge: "-10% Chegirma",
    badgeType: "sale",
    image:
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80",
    description:
      "Futuristik va dadil dizayn. Soat mexanizmining har bir harakatlanuvchi tishi va g'ildiragi ochiq ko'rinib turadigan xronograf skeletoni.",
  },
  {
    id: 7,
    name: "Apple Watch Ultra 2 Titanium",
    brand: "Apple",
    category: "smart",
    mechanism: "Aqlli mikroprotsessor S9 SiP",
    caseMaterial: "Aerokosmik titan",
    strapMaterial: "Okean silikon tasmasi",
    dialColor: "Always-On Retina OLED (3000 nit)",
    waterResistance: "100 metr / WR100",
    glass: "Mustahkam tekis sapfir",
    diameter: "49 mm",
    price: 10400000,
    oldPrice: 11900000,
    rating: 4.9,
    reviewsCount: 114,
    badge: "Smart Top",
    badgeType: "hot",
    image:
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
    description:
      "Ekstremal sport, dayving va kundalik hayot uchun eng qudratli smart soat. Ikki chastotali GPS, 72 soatgacha batareya va chuqurlik o'lchagich.",
  },
  {
    id: 8,
    name: "Casio G-Shock Mudmaster Carbon",
    brand: "Casio",
    category: "smart",
    mechanism: "Tough Solar kvarts",
    caseMaterial: "Karbon tola va qatron",
    strapMaterial: "Mustahkam polimer",
    dialColor: "Qora / Sariq indikator",
    waterResistance: "200 metr / 20 ATM",
    glass: "Mineral / Sapfir qoplama",
    diameter: "55 mm",
    price: 4200000,
    oldPrice: 4800000,
    rating: 4.8,
    reviewsCount: 65,
    badge: "Zarbalarga chidamli",
    badgeType: "featured",
    image:
      "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=800&q=80",
    description:
      "Har qanday og'ir sharoit, loy, chang va qattiq zarbalarga bardosh beruvchi afsonaviy Mudmaster. Quyosh batareyasi va kompas bilan jihozlangan.",
  },
  {
    id: 9,
    name: "Tag Heuer Carrera Chronograph",
    brand: "Tag Heuer",
    category: "erkaklar",
    mechanism: "Avtomatik Calibre Heuer 02",
    caseMaterial: "Sayqallangan po'lat",
    strapMaterial: "Perforatsiyalangan charm",
    dialColor: "Klassik ko'k quyosh nuri",
    waterResistance: "100 metr / 10 ATM",
    glass: "Gumbazsimon sapfir",
    diameter: "42 mm",
    price: 68000000,
    oldPrice: 75000000,
    rating: 4.8,
    reviewsCount: 23,
    badge: "Poyga Ruhi",
    badgeType: "featured",
    image:
      "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&w=800&q=80",
    description:
      "Avtopoygalar sharafiga yaratilgan tezlik va aniqlik ramzi. 80 soatlik quvvat zaxirasi va motopoyga uslubidagi premium charm tasma.",
  },
  {
    id: 10,
    name: "Seiko Presage Cocktail Time",
    brand: "Seiko",
    category: "klassik",
    mechanism: "Avtomatik 4R35 (Yaponiya)",
    caseMaterial: "Zanglamas po'lat",
    strapMaterial: "Jilolangan tabiiy charm",
    dialColor: "Moviy nur sochuvchi naqsh",
    waterResistance: "50 metr / 5 ATM",
    glass: "Hardlex qutbiy shisha",
    diameter: "40.5 mm",
    price: 6500000,
    oldPrice: 7200000,
    rating: 4.9,
    reviewsCount: 52,
    badge: "Bestseller",
    badgeType: "hot",
    image:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    description:
      "Tokiodagi elita barlar kokteyllaridan ilhomlangan yapon estetikasi. Chuqur gilyoshir qatlamli siferblat quyosh nurida ajoyib jilo beradi.",
  },
  {
    id: 11,
    name: "Jaeger-LeCoultre Reverso Classic",
    brand: "Jaeger-LeCoultre",
    category: "klassik",
    mechanism: "Mexanik (qo'lda burash)",
    caseMaterial: "18K oq oltin",
    strapMaterial: "Casa Fagliano buzoq terisi",
    dialColor: "Kumush va mat gilyosh",
    waterResistance: "30 metr / 3 ATM",
    glass: "Sapfir",
    diameter: "40 x 24.4 mm",
    price: 165000000,
    oldPrice: 180000000,
    rating: 5.0,
    reviewsCount: 14,
    badge: "Eksklyuziv",
    badgeType: "exclusive",
    image:
      "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=800&q=80",
    description:
      "Art-Deco uslubidagi afsonaviy buriluvchi korpus. 1931-yili polo o'yinchilari soat oynasini zarbalardan himoya qilishlari uchun ixtiro qilingan san'at asari.",
  },
  {
    id: 12,
    name: "Audemars Piguet Royal Oak Chrono",
    brand: "Audemars Piguet",
    category: "mexanik",
    mechanism: "Avtomatik xronograf",
    caseMaterial: "Zanglamas po'lat",
    strapMaterial: "Integrallashgan po'lat",
    dialColor: "Katta tapisseri ko'k",
    waterResistance: "50 metr / 5 ATM",
    glass: "Qirilmaydigan sapfir",
    diameter: "41 mm",
    price: 480000000,
    oldPrice: 520000000,
    rating: 5.0,
    reviewsCount: 29,
    badge: "VIP Premium",
    badgeType: "exclusive",
    image:
      "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&w=800&q=80",
    description:
      "Sakkiz burchakli mashhur bezel, ko'rinib turadigan 8 ta oltin bolt va Grande Tapisserie siferblati bilan jahon aristokratiyasining sevimli soati.",
  },
];

// O'zbekiston so'midan dollarga hisoblash kursi (masalan, 1 USD = 12,800 UZS)
const USD_RATE = 12800;

// Narxni chiroyli formatda chiqarish
function formatPrice(amount, currency = "UZS") {
  if (currency === "USD") {
    const usd = Math.round(amount / USD_RATE);
    return `$${usd.toLocaleString("en-US")}`;
  }
  return `${amount.toLocaleString("uz-UZ")} so'm`;
}
